/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Dare = IDL.Record({
  'id' : IDL.Nat,
  'dare' : IDL.Text,
  'caption' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllDares' : IDL.Func([], [IDL.Vec(Dare)], ['query']),
  'getDareById' : IDL.Func([IDL.Nat], [Dare], ['query']),
  'getDaresByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Dare)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Dare = IDL.Record({
    'id' : IDL.Nat,
    'dare' : IDL.Text,
    'caption' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllDares' : IDL.Func([], [IDL.Vec(Dare)], ['query']),
    'getDareById' : IDL.Func([IDL.Nat], [Dare], ['query']),
    'getDaresByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Dare)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };